
struct Domains {
    static let EmailDomains: [String] = ["gmail.com", "outlook.com", "icloud.com", "yahoo.com", "proton.me",
        "hotmail.com", "aol.com", "live.com", "me.com", "mail.com", "zoho.com",
        "gmx.com", "fastmail.com", "yandex.com", "protonmail.com", "inbox.com",
        "hushmail.com", "tutanota.com", "pm.me", "yopmail.com", "mail.ru",
        "qq.com", "163.com", "126.com", "rediffmail.com", "seznam.cz", "web.de",
        "gawab.com", "lycos.com", "bellsouth.net", "btinternet.com", "cox.net",
        "comcast.net", "verizon.net", "att.net", "sbcglobal.net", "earthlink.net",
        "rocketmail.com", "optonline.net", "shaw.ca", "telus.net", "live.co.uk",
        "sky.com", "btopenworld.com", "virginmedia.com", "talktalk.net", "orange.fr",
        "laposte.net", "t-online.de", "freenet.de", "online.de", "home.nl", "ziggo.nl",
        "wanadoo.fr", "sfr.fr", "alice.it", "libero.it", "tin.it", "virgilio.it",
        "mailinator.com", "tempmail.com", "trashmail.com", "guerrillamail.com",
        "mintemail.com", "fakeinbox.com", "maildrop.cc", "getnada.com", "anonymbox.com",
        "dispostable.com", "spamgourmet.com", "yandex.ru", "bk.ru", "list.ru",
        "mail.ua", "ukr.net", "i.ua", "bigmir.net", "inbox.lv", "mail.ee", "mail.bg",
        "abv.bg", "webmail.co.za", "mweb.co.za", "tiscali.co.uk", "ntlworld.com",
        "virgin.net", "blueyonder.co.uk", "btconnect.com", "skyrocket.com", "talk21.com",
        "netzero.net", "juno.com", "mail.comcast.net", "earthlink.net", "cfl.rr.com",
        "bellsouth.net", "sbcglobal.net", "msn.com", "windowslive.com", "hotmail.co.uk",
        "googlemail.com", "gmail.co.uk", "hotmail.fr", "free.fr", "laposte.net", "numericable.fr",
        "sfr.fr", "orange.fr", "neuf.fr", "club-internet.fr", "aliceadsl.fr",
        "bol.com.br", "uol.com.br", "terra.com.br", "ig.com.br", "globo.com",
        "bol.com", "ziggo.nl", "kpnmail.nl", "planet.nl", "chello.nl", "home.nl",
        "tele2.nl", "wanadoo.nl", "xs4all.nl", "libero.it", "tiscali.it", "virgilio.it",
        "alice.it", "tin.it", "hotmail.it", "yahoo.it", "live.it", "mail.ru", "inbox.ru",
        "bk.ru", "list.ru", "rambler.ru", "mail.kz", "mail.by", "mail.ua", "ukr.net",
        "i.ua", "bigmir.net", "abv.bg", "mail.bg", "mail.ee", "inbox.lv", "mail.lv",
        "mail.md", "mail.am", "mail.ge", "mail.az", "yandex.ua", "yandex.kz", "yandex.by"
    ]

    static let WebsiteDomain: [String] = ["gmail.com", "outlook.com", "icloud.com", "yahoo.com", "proton.me",
        "hotmail.com", "aol.com", "live.com", "me.com", "mail.com", "zoho.com",
        "gmx.com", "fastmail.com", "yandex.com", "protonmail.com", "inbox.com",
        "hushmail.com", "tutanota.com", "pm.me", "yopmail.com", "mail.ru",
        "qq.com", "163.com", "126.com", "rediffmail.com", "seznam.cz", "web.de",
        "gawab.com", "lycos.com", "bellsouth.net", "btinternet.com", "cox.net",
        "comcast.net", "verizon.net", "att.net", "sbcglobal.net", "earthlink.net",
        "rocketmail.com", "optonline.net", "shaw.ca", "telus.net", "live.co.uk",
        "sky.com", "btopenworld.com", "virginmedia.com", "talktalk.net", "orange.fr",
        "laposte.net", "t-online.de", "freenet.de", "online.de", "home.nl", "ziggo.nl",
        "wanadoo.fr", "sfr.fr", "alice.it", "libero.it", "tin.it", "virgilio.it",
        "mailinator.com", "tempmail.com", "trashmail.com", "guerrillamail.com",
        "mintemail.com", "fakeinbox.com", "maildrop.cc", "getnada.com", "anonymbox.com",
        "dispostable.com", "spamgourmet.com", "yandex.ru", "bk.ru", "list.ru",
        "mail.ua", "ukr.net", "i.ua", "bigmir.net", "inbox.lv", "mail.ee", "mail.bg",
        "abv.bg", "webmail.co.za", "mweb.co.za", "tiscali.co.uk", "ntlworld.com",
        "virgin.net", "blueyonder.co.uk", "btconnect.com", "skyrocket.com", "talk21.com",
        "netzero.net", "juno.com", "mail.comcast.net", "earthlink.net", "cfl.rr.com",
        "bellsouth.net", "sbcglobal.net", "msn.com", "windowslive.com", "hotmail.co.uk",
        "googlemail.com", "gmail.co.uk", "hotmail.fr", "free.fr", "laposte.net", "numericable.fr",
        "sfr.fr", "orange.fr", "neuf.fr", "club-internet.fr", "aliceadsl.fr",
        "bol.com.br", "uol.com.br", "terra.com.br", "ig.com.br", "globo.com",
        "bol.com", "ziggo.nl", "kpnmail.nl", "planet.nl", "chello.nl", "home.nl",
        "tele2.nl", "wanadoo.nl", "xs4all.nl", "libero.it", "tiscali.it", "virgilio.it",
        "alice.it", "tin.it", "hotmail.it", "yahoo.it", "live.it", "mail.ru", "inbox.ru",
        "bk.ru", "list.ru", "rambler.ru", "mail.kz", "mail.by", "mail.ua", "ukr.net",
        "i.ua", "bigmir.net", "abv.bg", "mail.bg", "mail.ee", "inbox.lv", "mail.lv",
        "mail.md", "mail.am", "mail.ge", "mail.az", "yandex.ua", "yandex.kz", "yandex.by"
    ]
    
    static let Domains: [String] = [
        "Google", "Gmail", "Facebook", "Apple", "GitHub", "Twitter", "Instagram",
        "LinkedIn", "Slack", "Reddit", "Dropbox", "Microsoft", "Zoom", "Amazon",
        "Netflix", "Spotify", "Pinterest", "Trello", "Asana", "Yahoo", "ProtonMail",
        "Discord", "TikTok", "WhatsApp", "Snapchat", "Figma", "Notion", "Bitbucket",
        "Medium", "StackOverflow", "WordPress", "Salesforce", "PayPal", "Venmo",
        "Square", "Stripe", "Shopify", "Evernote", "OneDrive", "Google Drive",
        "Microsoft Teams", "YouTube", "Twitch", "SoundCloud", "Telegram", "Signal",
        "ProtonVPN", "NordVPN", "ExpressVPN", "DuckDuckGo", "1Password", "LastPass",
        "Bitwarden", "Keeper", "ProtonCalendar", "ProtonContacts", "Canva", "Behance",
        "Dribbble", "OpenAI", "ChatGPT", "Slack", "ZoomInfo", "Calendly", "Adobe",
        "Fiverr", "Upwork", "Coursera", "Udemy", "Khan Academy", "Duolingo",
        "Airbnb", "TripAdvisor", "Booking.com", "Expedia", "Hulu", "Disney+", "HBO Max",
        "Vimeo", "WeTransfer", "Soundtrap", "Trello", "Notability", "GoodNotes",
        "Microsoft Office", "Google Docs", "Google Sheets", "Google Slides",
        "Adobe Illustrator", "Adobe Photoshop", "Adobe Premiere", "Sketch",
        "InVision", "Miro", "Lucidchart", "GitLab", "Bitrise", "CircleCI", "Jira",
        "Confluence", "Zendesk", "Freshdesk", "Intercom", "HubSpot", "Mailchimp",
        "SendGrid", "ActiveCampaign", "Campaign Monitor", "AWeber", "Typeform",
        "SurveyMonkey", "Eventbrite", "Meetup", "GitKraken", "Kaggle", "Tableau",
        "Power BI", "Notion AI", "Obsidian", "Roam Research", "Toggl", "Clockify",
        "RescueTime", "Todoist", "Microsoft To Do", "Google Keep", "Evernote Teams",
        "Basecamp", "ClickUp", "Monday.com", "Zoho Projects", "Wrike", "Smartsheet",
        "Assembla", "Teamwork", "Redbooth", "Harvest", "OmniFocus", "Things",
        "Goodreads", "Coursera", "EdX", "Skillshare", "Pluralsight", "LinkedIn Learning",
        "Codecademy", "Treehouse", "LeetCode", "HackerRank", "Codewars", "Exercism",
        "Project Euler", "Hack The Box", "TryHackMe", "Cybersecurity Lab", "MIT OpenCourseWare",
        "Stanford Online", "Harvard Online", "Udacity", "Simplilearn", "DataCamp",
        "OpenAI API", "DeepL", "Grammarly", "Hemingway", "QuillBot", "Reverso", "Wordtune",
        "Notion AI", "Copy.ai", "Jasper", "Writesonic", "AI Dungeon", "Sudowrite",
        "Canva AI", "RunwayML", "Luma AI", "Synthesia", "D-ID", "Murf.ai", "Pictory",
        "Synthesys", "AIVA", "Boomy", "Soundraw", "Endel", "Calm", "Headspace",
        "Insight Timer", "BetterSleep", "Noisli", "RainyMood", "Focus@Will", "MyNoise",
        "Todo.vu", "Planoly", "Later", "Buffer", "Hootsuite", "Sprout Social",
        "Crowdfire", "Tailwind", "PromoRepublic", "Zoho Social", "SocialPilot",
        "Sendible", "Agorapulse", "Mavenlink", "Workfront", "Clarizen", "LiquidPlanner",
        "Freedcamp", "nTask", "ProofHub", "TeamGantt", "Bit.ai", "Slite", "Nuclino",
        "Tettra", "Guru", "Slab", "Bloomfire", "Confluence", "Notion Wiki", "MediaWiki",
        "DokuWiki", "TikiWiki", "XWiki", "Zoho Wiki", "Proton Wiki"
    ]
    
}


// MARK: - Extensive Service Names
// let serviceSuggestions = sSuggestions.alls
